language: android
dist: trusty
env:
  global:
    - EMU_FLAVOR=default
    - ADB_INSTALL_TIMEOUT=16
    - ANDROID_HOME=/usr/local/android-sdk
    - ANDROID_SDK_ROOT=${ANDROID_HOME}
    - TOOLS=${ANDROID_HOME}/tools
    - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}
  matrix:
    - API=19 ABI=x86
    #- API=21 ABI=armeabi-v7a
    #- API=24 ABI=arm64-v8a
    - API=29 ABI=x86_64
before_install:
  - mkdir -p $ANDROID_HOME/licenses
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_HOME/licenses/android-sdk-license
install:
  - yes | sdkmanager "platform-tools" > /dev/null
  - yes | sdkmanager "tools" > /dev/null
  - yes | sdkmanager "build-tools;29.0.2" > /dev/null
  - yes | sdkmanager "platforms;android-$API" > /dev/null
  - yes | sdkmanager "platforms;android-29" > /dev/null
  - yes | sdkmanager "ndk-bundle" > /dev/null
  - yes | sdkmanager "cmake;3.10.2.4988404" > /dev/null
  - yes | sdkmanager "emulator" > /dev/null
  - yes | sdkmanager "extras;android;m2repository" > /dev/null
  - yes | sdkmanager "system-images;android-$API;$EMU_FLAVOR;$ABI" > /dev/null
before_script:
  - echo no | avdmanager create avd --force -n test -k "system-images;android-$API;$EMU_FLAVOR;$ABI" -c 10M
  - QEMU_AUDIO_DRV=none emulator -verbose -avd test -no-audio -no-accel -no-snapshot -no-window -camera-back none -camera-front none -selinux permissive -qemu -m 2048 &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
  - ./gradlew build connectedCheck
